# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98dc6bd716212d2f019e825de070a96b66d1a6dd7a345827dfa45b762b3306e90edee408337d6ba836a26538f741eaa451a22fa481a31ebc47e96d611c60aac

test:
  secret_key_base: d41ff343e551a3323fd554e64a13e1ef9dfc2e3d98f2422a49e1b7a7a3a2d1cac7dc98f71f138bbb93bc2f6548e499ff8f608031580a171c4090925b4d1cdee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
